/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.CardLayout;

/**
 *
 * @author Pedro
 */
public class TelaCardLayout extends javax.swing.JFrame {

    /**
     * Creates new form TelaCardLayout
     */
    public TelaCardLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlOutubroRosa = new javax.swing.JPanel();
        pnlNovembroAzul = new javax.swing.JPanel();
        mnuPrincipal = new javax.swing.JMenuBar();
        mnuTelas = new javax.swing.JMenu();
        mnuOutubroRosa = new javax.swing.JMenuItem();
        mnuNovembroAzul = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Card Layout");

        pnlPrincipal.setLayout(new java.awt.CardLayout());

        pnlOutubroRosa.setBackground(new java.awt.Color(255, 153, 255));

        javax.swing.GroupLayout pnlOutubroRosaLayout = new javax.swing.GroupLayout(pnlOutubroRosa);
        pnlOutubroRosa.setLayout(pnlOutubroRosaLayout);
        pnlOutubroRosaLayout.setHorizontalGroup(
            pnlOutubroRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlOutubroRosaLayout.setVerticalGroup(
            pnlOutubroRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pnlPrincipal.add(pnlOutubroRosa, "Outubro_Rosa");

        pnlNovembroAzul.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout pnlNovembroAzulLayout = new javax.swing.GroupLayout(pnlNovembroAzul);
        pnlNovembroAzul.setLayout(pnlNovembroAzulLayout);
        pnlNovembroAzulLayout.setHorizontalGroup(
            pnlNovembroAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlNovembroAzulLayout.setVerticalGroup(
            pnlNovembroAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pnlPrincipal.add(pnlNovembroAzul, "Novembro_Azul");

        mnuTelas.setText("Telas");

        mnuOutubroRosa.setText("Outubro Rosa");
        mnuOutubroRosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOutubroRosaActionPerformed(evt);
            }
        });
        mnuTelas.add(mnuOutubroRosa);

        mnuNovembroAzul.setText("Novembro Azul");
        mnuNovembroAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNovembroAzulActionPerformed(evt);
            }
        });
        mnuTelas.add(mnuNovembroAzul);

        mnuPrincipal.add(mnuTelas);

        setJMenuBar(mnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuOutubroRosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOutubroRosaActionPerformed
        CardLayout clOutubro = (CardLayout) pnlPrincipal.getLayout();
        clOutubro.show(pnlPrincipal, "Outubro_Rosa");
    }//GEN-LAST:event_mnuOutubroRosaActionPerformed

    private void mnuNovembroAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNovembroAzulActionPerformed
        CardLayout clOutubro = (CardLayout) pnlPrincipal.getLayout();
        clOutubro.show(pnlPrincipal, "Novembro_Azul");
    }//GEN-LAST:event_mnuNovembroAzulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCardLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem mnuNovembroAzul;
    private javax.swing.JMenuItem mnuOutubroRosa;
    private javax.swing.JMenuBar mnuPrincipal;
    private javax.swing.JMenu mnuTelas;
    private javax.swing.JPanel pnlNovembroAzul;
    private javax.swing.JPanel pnlOutubroRosa;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
